src/App.php, src/Request.php, src/Route.php, tests/AppTest.php, tests/RouteTest.php
Added support for running hooks only for specific groups of routes
=> Middlewares

README.md
linked libraries
1. Image
2. Preloader
3. Storage
4. Analytics
=> Link to other libraries

src/App.php
- prevents a callback with a self reference, that causes memory leaks when call inside `call_user_func_array`
=> fix(app): self reference in a callback causing memory leak

src/Request.php, tests/RequestTest.php
Adds content range header parser and relevant getters to get the content range start, content range end, content range size and content range unit
=> feat-range-parser

src/Response.php, tests/e2e/ResponseTest.php, tests/e2e/server.php
Fix issue with status code caused by last update
=> fix-status-code

src/App.php, src/Route.php, tests/RouteTest.php
Rename URL to path,
getURL -> getPath
getAliasUrl -> getAliasPath
=> refactor - rename URL to path

composer.lock, src/Validator/Hostname.php, tests/Validator/HostnameTest.php
Added a hostname validator that can be used instead of our current `Text` validator for hostnames. Key features:
- Validates that port, protocol and route is not part of the hostname
- Supports wildcard whitelists. `matej.app.com` is a valid hostname for pattern `*.app.com`
This PR will be useful for Appwrite for:
- Adding new platform
- Preparing CORS for request
This will let Appwrite validate if a platform was added properly, and add wildcard support.
Tests added ✅
=> Feat: Hostname validator

.travis.yml, composer.lock, src/Validator/Hostname.php, tests/Validator/HostnameTest.php
We needed to use 2 validators: Text and Hostname. Now hostname properly checks for length, and is more secure.
- New tests added
=> Feat: Hostname max length

.travis.yml, src/Response.php, src/Validator/ArrayList.php, tests/ResponseTest.php, tests/Validator/ArrayListTest.php
- Expose response status code publicly
- Expose nested validators publicly
=> Feat graphql helpers

src/App.php, tests/AppTest.php
make addRoute public to easily use it in new `utopia-php/platform` library
ref: https://github.com/utopia-php/platform/pull/1
=> make addRoute public

README.md, src/App.php, src/Hook.php, src/Route.php, tests/AppTest.php, tests/HookTest.php
- Updated readme
- Unit test to Hook
=> Hook Unit test and Readme update

src/App.php, tests/AppTest.php
Allow re-matching route from request by passing fresh parameter
Supersedes #60
=> Allow fetching fresh route match

src/App.php, src/Response.php, src/Route.php, tests/HookTest.php, tests/RouteTest.php
disable route output if response already sent
=> Feat disable route if response sent

src/App.php, src/Response.php, src/View.php
For better auto-completion when we extend our base classes.
=> Updated return types fro self to static

Dockerfile, composer.json, composer.lock, psalm.xml, src/App.php, src/Response.php, src/Validator/Hostname.php, src/View.php, tests/AppTest.php, tests/HookTest.php, tests/RequestTest.php, tests/ResponseTest.php, tests/RouteTest.php, tests/UtopiaRequestTest.php, tests/Validator/ArrayListTest.php, tests/Validator/AssocTest.php, tests/Validator/BooleanTest.php, tests/Validator/FloatValidatorTest.php, tests/Validator/HexColorTest.php, tests/Validator/HostnameTest.php, tests/Validator/IntegerTest.php, tests/Validator/JSONTest.php, tests/Validator/NumericTest.php, tests/Validator/RangeTest.php, tests/Validator/TextTest.php, tests/Validator/WhiteListTest.php, tests/Validator/WildcardTest.php, tests/ViewTest.php
What changed:
- using composer install over update to not change the lock file (bad practice)
- update `phpunit` and `psalm`
- removed unnecessary condition in Hostname validator
- add better typings
- cleaned up tests
- made tests more independent from each other
- migrated to proper naming conventions for all tests
- added more tests for route matching
- increase psalm level to `3` 🥳
=> feat: overall improvements

src/Request.php
- Add static returns for setters
=> Feat setter returns

composer.lock, src/Request.php, tests/AppTest.php, tests/RequestTest.php
Implements `getHeaders` method that returns array of all request haders.
=> Feat: Request->getHeaders()

src/App.php, tests/AppTest.php
Wildcard route and corresponding test
=> Wildcard route support

src/Validator/Domain.php, src/Validator/Host.php, src/Validator/IP.php, src/Validator/URL.php, tests/Validator/DomainTest.php, tests/Validator/HostTest.php, tests/Validator/IPTest.php, tests/Validator/URLTest.php
This PR will bring the following validators from Appwrite into Utopia:
```
Domain
Host
IP
URL
```
=> Backport Appwrite Validators to Utopia

composer.lock, src/App.php, src/Hook.php, src/Validator/Nullable.php, src/Validator/Text.php, tests/AppTest.php, tests/Validator/TextTest.php
=> feat: handle null param

src/Validator/Nullable.php, tests/Validator/NullableTest.php
- adds `getValidator` method to `Nullable` validator
- adds some tests
=> feat: add return validator to nullable

src/App.php, tests/AppTest.php
- adds support for trailing wildcard `/my/root/*`
=> feat: trailing wildcards

.github/ISSUE_TEMPLATE/bug.yaml, .github/workflows/test.yml, CONTRIBUTING.md, README.md, composer.json, composer.lock, docs/Getting-Starting-Guide.md, example/composer.json, tests/Validator/DomainTest.php, tests/Validator/HostTest.php, tests/Validator/IPTest.php, tests/Validator/URLTest.php
Rename from utopia/framework to utopia/http
=> Docs: Improve readme

src/Http/Response.php
Allow 451 status code to be thrown
=> Add 451 status code

composer.json, composer.lock, src/App.php, tests/AppTest.php
The original PR was merged to the 0.32.x branch, when it had to be merged into `0.33.x` instead
https://github.com/utopia-php/http/pull/124
=> Feat default param callable

composer.json, composer.lock
Adding the Tests namespace causes conflicts downstream.
=> fix: remove tests from autoload

.github/workflows/test.yml, composer.lock, src/Validator/AnyOf.php, tests/Validator/MultipleOfTest.php
Nessessary to do proper specs generation.
=> Feat: AnyOf validators export

composer.lock, src/Http/Validator/ArrayList.php
Only if the validator contains value
=> fix: adding a validator description to the arraylist

composer.lock, src/Response.php
Some responses weren't being compressed due to irregular mimeTypes.
Adds an more robust check based on Cloudflare's list here: https://developers.cloudflare.com/speed/optimization/content/compression/
=> feat: compress more types

README.md, composer.json, composer.lock, src/Http/Adapter/FPM/Request.php, src/Http/Adapter/FPM/Response.php, src/Http/Adapter/Swoole/Request.php, src/Http/Adapter/Swoole/Response.php, src/Http/Adapter/Swoole/Server.php, src/Http/Files.php, src/Http/Http.php, src/Http/Request.php, src/Http/Response.php, src/Http/Validator/AllOf.php, src/Http/Validator/AnyOf.php, src/Http/Validator/ArrayList.php, src/Http/Validator/NoneOf.php, tests/ResponseTest.php, tests/e2e/BaseTest.php, tests/e2e/init.php
Fixes tests (formatting, code quality)
Adds cookie header to swoole server properly
Adds test for cookies
=> Fix: Cookie headers

composer.json, composer.lock, src/Response.php, tests/e2e/Client.php, tests/e2e/ResponseTest.php, tests/e2e/server.php
sync partially with 0.34.x too
Inspiration: https://github.com/utopia-php/http/pull/182
(plus diff between 0.33.x and 0.34.x)
=> Feat: array-like headers
