utopia-php/http

- src/Validator/FloatValidator.php
- src/Validator/Integer.php
- tests/Validator/FloatValidatorTest.php
- tests/Validator/IntegerTest.php
Add loose validations to integer and float validators to accept integer and float strings respectively, useful for query params validation
> update integer and float validator tests to test loose condition

- src/Validator/WhiteList.php
- tests/Validator/WhiteListTest.php
This PR updates the whitelist validator to not accept arrays - even though the validator is constructed from arrays, values tested against the validator are not arrays.
**Testing** 
Unit tests have been updated to reflect this change.
> Fix: whitelist validator should reject arrays of values

- src/Response.php
1. Cookie names are case insensitive
2. We have unique ids in our cookie names which are case insensitive in MariaDB
3. We are lowercasing cookie name while calling getCookie on utopia-swoole
> Set cookie name to lowercase

- src/Validator/Assoc.php
- tests/Validator/AssocTest.php
This PR sets maximum limit for ASOC object to 64kB, so it can be stored as TEXT in database (255...65535).
Related PR: https://github.com/appwrite/appwrite/pull/2486
> Limited assoc to 64kB

- src/App.php
- tests/AppTest.php
- tests/UtopiaRequestTest.php
This allows running code that required `->match()` before Utopia gets parameters. This is important, because you cannot write such a code before running `->run()`, because at the top of `run` we do some sorting of `$routes`, and for that to work properly, we need to run `->match()` after running this sorting.
Not sure how to re-write tests. A lot of tests send empty args array, some send specific args that we test. I also removed the default value that can cause some troubles.
> Run getParams after init

- src/Response.php
In Appwrite, cookies were set with an expiry of the session: https://github.com/appwrite/appwrite/issues/3080
There was a miss-match between Framework and Swoole, one naming it `expire`, one `expires`:
Swoole: https://github.com/utopia-php/swoole/blob/master/src/Swoole/Response.php#L91
PHP: https://github.com/utopia-php/framework/blob/master/src/Response.php#L591
The reason for this is because PHP `setcookie()` expects `expires`, so it was probably a quick patch from earlier.
I decided to stick with `expire`, as this keyword is used all around the Framework library, as well as in Swoole.
I added a step before using PHP setcookie, to rename the parameter to what is expected by this built-in PHP method.
Expiry should now work properly.
I did manual QA in Appwrite using this branch, ensuring …
> Fix: Cookies expiry

- composer.lock
- src/Validator/Hostname.php
- tests/Validator/HostnameTest.php
Now we also allow `*` or `vercel.*` as hostnames.
Issue: https://github.com/appwrite/appwrite/issues/2939
Inside Appwrite, `*` is not actually returned as a header, instead, a specific domain is found and passed in the header. No need to worry about the security part, Apwrite handles it. Regarding "Secure by default", we can show noticeable alert saying `*`shouldn't be used for reasons of being lazy, instead, only if your project requires this configuration (for instance Wordpress plugin).
Regarding `vercel.*`, I don't think anyone would use it.. But that doesn't really matter we shouldn't support it if we can. I would say same as previous, could be insecure, but people are aware because they type it in.
> Feat: Improved hostname validator

- src/App.php
- Request filters in Appwrite were failing, as previous change did not account for the fact that hooks might update request params itself, this change accounts for that
- Options hooks was not updated with the change, this fixes that
> Fix options hooks + Fix when init hooks modify request

- src/Request.php
- tests/RequestTest.php
Adds getters/setters (to avoid directly mutating the underlying structure in Appwrite GraphQL)
- Allow setting request method
- Allow setting request URI
- Allow setting and removing headers
- Allow setting $_GET and $_POST
- Allow getting request raw payload
https://github.com/utopia-php/swoole/pull/24
https://github.com/appwrite/appwrite/pull/974
> Feat allow mutations

- src/App.php
Before, the logs provided very little context about what really happened:
```
appwrite  | [Error] Type: Utopia\Exception
appwrite  | [Error] Message: Error handler had an error
appwrite  | [Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
appwrite  | [Error] Line: 610
```
After this, at least, the message will include the underlying error:
```
appwrite  | [Error] Type: Utopia\Exception
appwrite  | [Error] Message: Error handler had an error: Can't find FULLTEXT index matching the column list
appwrite  | [Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
appwrite  | [Error] Line: 610
```
Related:
* https://github.com/appwrite/appwrite/issues/4535
> Update error handler to include message from previous error

- src/App.php
- src/Route.php
- tests/AppTest.php
- tests/RouteTest.php
Previously, it was only possible to set 1 alias on a route. This PR updates Route to support multiple aliases and App to handle requests against all aliases.
> Add support for multiple aliases

- src/App.php
On multithreaded environments, the `request` and `response` set in `run(...)` can run into a race condition when the static callback is called after a different request has overwritten its callback.
This forces the resource to be set initially.
> fix: race condition for request/response resources

- src/App.php
To allow wrapping/transforming exceptions in a group hook that is then used in the global hook without being overridden
> Allow overriding the error resource from group to global hook

- src/Validator/Hostname.php
- tests/Validator/HostnameTest.php
Problems with previous solution:
- Too complex
- Allowed multiple wildcards like `*.*.gitpod.io` which is not allowed by standard
- Wildcard only allowed one level of subdomain, not all of them
- Wildcard was allowed in middle of domain like `api.*.com` and `myapp.*`. Again, not part of standard
> Feat: Improve hostname validator

- src/App.php
- tests/AppTest.php
- Added a check to ensure that the matched URL has the same amount of segments (separated by `/`) as the route. This ensures that a URL will not match an incorrect route if parameters are missing.
- Added new tests to ensure correct matching
> Fix route mismatch against shorter paths when params are missing

- src/App.php
- src/Router.php
- tests/AppTest.php
- Option to allow overriding routes
> allow overriding routes

- composer.lock
- phpstan.neon
- src/Http/Adapter/Swoole/Server.php
- src/Http/Http.php
- src/Http/Validator/Assoc.php
- tests/e2e/ResponseSwooleTest.php
- tests/e2e/server_swoole.php
This is proper usage of coroutine http server in Swoole. It prevents error when trying to apply v2 in executor
```
openruntimes-executor  | 
openruntimes-executor  | Warning: Swoole\Server::start(): eventLoop has already been created, unable to start Swoole\Http\Server in /usr/local/vendor/utopia-php/framework/src/Http/Adapter/Swoole/Server.php on line 65
```
> Fix: Swoole coroutine http server

- src/Validator/ArrayList.php
- tests/Validator/ArrayListTest.php
When making Appwrite endpoint to send 10 test mails, I noticed error for when I add 11 mails isn't very useful. This will make it clear that validation fails because of exceeded lenght.
> Feat: Improve ArrayList description

- src/Response.php
> Add 451 error code

- src/Http/Adapter/FPM/Response.php
- src/Http/Adapter/Swoole/Response.php
- src/Http/Response.php
Make intrerfaces public to allow chunk response
> Fix: Missing interfaces

- composer.lock
- src/App.php
- tests/AppTest.php
In this PR https://github.com/utopia-php/http/pull/127 we introduced the ability to make default params callable. 
However there was a bug in the code that resulted in the argument passed by the user being called. This PR fixes it
> chore: fix default param

- .gitignore
- src/Http/Router.php
- tests/RouterTest.php
This PR addresses an issue where numeric segments in the path, such as 0, were being filtered out due to the default behavior of array_filter.
**Before Change:** The segment 0 would be filtered out, potentially causing a 404 error or incorrect route matching.
**After Change:** The segment 0 is preserved, ensuring the correct route is matched.
The following changes have been made:
Updated the array_filter call to use a lambda function that filters out only empty strings, ensuring numeric segments like `0` are preserved.
Added a test case to verify that 0 is correctly matched in the path.
> Fix: preserve numeric segments in path matching

- CONTRIBUTING.md
This PR updates the testing instructions in the `CONTRIBUTING.md` file to reflect the current code implementation. The previous instructions were outdated and didn't run the tests. This update ensures that tests are run in the correct containers.
- Change testing instructions to use `fpm`
- Remove instructions for running PHPUnit and Psalm in the `web` container as it no longer matches the current implementation
> Update testing instructions in CONTRIBUTING.md

- README.md
updated to the correct syntax in `README.md` according to this -> https://github.com/utopia-php/di/blob/22490c95f7ac3898ed1c33f1b1b5dd577305ee31/src/DI/Container.php#L37
> fix: incorrect syntax for adding dependency to container

- src/Http/Adapter/FPM/Request.php
- src/Http/Adapter/Swoole/Request.php
- src/Http/Adapter/Swoole/Server.php
- src/Http/Adapter/SwooleCoroutine/Server.php
- src/Http/Files.php
- src/Http/Http.php
- src/Http/Request.php
- src/Http/Response.php
- tests/HttpTest.php
fixes the warnings and errors generated due to implicit marking of null on various parameters
> fix: implicit null warnings for test

- composer.lock
- src/App.php
- src/Route.php
- src/Router.php
- tests/e2e/Client.php
- tests/e2e/ResponseTest.php
- tests/e2e/server.php
Ensure parameters in path work prorperly with alias
> Fix: Alias parameters

- src/Http/Adapter/FPM/Response.php
- src/Http/Adapter/Swoole/Response.php
- src/Http/Response.php
- tests/e2e/BaseTest.php
- tests/e2e/Client.php
- tests/e2e/init.php
Important for headeers like www-authenticate, or set-cookie
> Feat: Allow array for headers

- src/Response.php
- tests/e2e/ResponseTest.php
- tests/e2e/server.php
Marks default as true, which is how it behaved beforehand; this should prevent some rare issues, like  double CORS brought by community
> Fix: override default (backwards compatibility)
